var letters = {
	"a": [0b1, "a", "A", "@", "ä", "α", "À", "Á", "Â", "Ã", "Ä", "Å", "ª", "₳"],
	"b": [0b1, "b", "B", "6", "₿", "ß", "฿"],
	"c": [0b1, "c", "C", "(", "©", "Ç", "©", "¢", "￠", "₡"],
	"d": [0b1, "d", "D", "Ð", "𐐀"],
	"e": [0b1, "e", "E", "3", "³", "€", "È", "É", "Ê", "Ë", "£", "￡", "ę", "ε", "₤"],
	"f": [0b1, "f", "F"],
	"g": [0b1, "g", "G"],
	"h": [0b1, "h", "H", "ㅐ"],
	"i": [0b1, "i", "I", "!", "1", "|", "Ì", "Í", "Î", "Ï", "Ĩ", "ĩ", "Ī", "ī", "Ĭ", "ĭ", "Į", "į", "İ", "ı", "ㅣ", "¡", "¦"],
	"j": [0b1, "j", "J", "Į", "į", "Ĵ", "ĵ"],
	"k": [0b1, "k", "K", "Ķ", "ķ", "ĸ"],
	"l": [0b1, "l", "L", "i", "I", "!", "1", "|", "Ì", "Í", "Î", "Ï", "Ĩ", "ĩ", "Ī", "ī", "Ĭ", "ĭ", "Į", "į", "İ", "ı", "Ĺ", "Ļ", "Ł", "ł", "ĺ", "ļ"],
	"m": [0b1, "m", "M", "ՠ", "ա", "൩", "൱", "ก", "ด", "ต", "ถ", "ท", "₥", "₼"],
	"n": [0b1, "n", "N", "Ń", "ń", "Ņ", "ņ", "Ň", "ň", "ŉ", "Ŋ", "h", "ŋ", "ղ", "ո", "ח", "൨", "ภ", "∩", "₦"],
	"o": [0b1, "o", "O", "ö", "0", "°", "Ō", "ō", "Ŏ", "ŏ", "Ő", "ő", "θ", "օ", "ഠ", "൦", "ㅇ", "σ"],
	"p": [0b1, "p", "P", "₱"],
	"q": [0b1, "q", "Q", "θ"],
	"r": [0b1, "r", "R", "®", "Ŕ", "ŕ", "Ŗ", "ŗ", "Ř", "ř","ʳ", "®", "Γ", "₹"],
	"s": [0b1, "s", "S", "$", "§","Š", "š", "Ś", "ś", "ಽ", "ട", "﹩", "＄", "₷"],
	"t": [0b1, "t", "T", "+", "±", "τ", "₸"],
	"u": [0b1, "u", "U", "ü", "µ", "ն", "մ", "น", "บ", "ป"],
	"v": [0b1, "v", "V"],
	"w": [0b1, "w", "W", "ա", "ผ", "ฝ", "พ", "ฟ", "￦", "₩"],
	"x": [0b1, "x", "X", "×"],
	"y": [0b1, "y", "Y", "Ÿ", "¥", "￥"],
	"z": [0b1, "z", "Z", "ž", "Ź"],
	"ß": [0b1, "ß", "ẞ", "s", "S"],
	"ä": [0b1, "ä"],
	"ö": [0b1, "ö"],
	"ü": [0b1, "ü"],
	"1": [0b0, "1", "i", "I", "!", "|", "Ì", "Í", "Î", "Ï", "Ĩ", "ĩ", "Ī", "ī", "Ĭ", "ĭ", "Į", "į", "İ", "ı"],
	"2": [0b0, "2", "²"],
	"3": [0b0, "3", "³"],
	"4": [0b0, "4", "A"],
	"5": [0b0, "5", "S"],
	"6": [0b0, "6", "b"],
	"7": [0b0, "7", "/"],
	"8": [0b0, "8", "B"],
	"9": [0b0, "9", "g"],
	"0": [0b0, "0", "O", "o", "°", "θ"],
	" ": [0b0, "\\s", ".", ",", "-", "_"],
	"-": [0b0, "-", "ㅡ", "—"],
	"+": [0b0, "+"],
	"?": [0b0, "?", "¿"],
	"!": [0b0, "!", "|"],
	"/": [0b0, "/"],
	"\\": [0b0, "\\"]
};

var multiLetters = { // This is not implemented yet, just a "dummy-ish" object containing data for future use
	"aa": ["ㅆ", "ㅃ"],
	"ae": ["Æ", "æ"],
	"tm": ["™"],
	"yen": ["¥", "￥"],
	"dz": ["Ǳ", "ǲ", "ǳ"],
	"cc": ["ㄸ"]
}

const incompatibleLetters = {
	teamspeak: [],
	yatqaAlways: [],
	yatqaImport: ["¦", "|", "𐐨", "𐐀"],
	sinusbot: []
}

const reasons = reason = {
	spam: "Spam",
	impersonation: "Impersonation",
	adminImpersonation: "Impersonation of admin",
	test: "TEST - This shouldn't have happened. You're free to reconnect once this mistake is fixed. Big sorry!",
	obscene: "We don't use such words here...",
	undefined: "Reason unknown",
	defaultName: "Your nickname has to be more unique",
	characters: {
		bloodType: "You can't use blood-type emojis in your nickname.",
		control: "Your nickname can't contain control-characters.",
		mathDoubleStruckUpper: "You can't have Mathematical Double-Struck Letters in your nickname.",
		mathDoubleStruckLower: "You can't have Mathematical Double-Struck Letters in your nickname.",
		consSpace: "You can't have 3 or more consecutive spaces in your nickname.",
		fakeF: "You can't have weird versions of 'F' in your nickname.",
		fakeG: "You can't have weird versions of 'G' in your nickname.",
		fakeK: "You can't have weird versions of 'K' in your nickname.",
		fakeL: "You can't have weird versions of 'L' in your nickname.",
		fakeM: "You can't have weird versions of 'M' in your nickname.",
		fakeN: "You can't have weird versions of 'N' in your nickname.",
		fakeO: "You can't have weird versions of 'O' in your nickname.",
		fakeS: "You can't have weird versions of 'S' in your nickname.",
		fakeR: "You can't have weird versions of 'R' in your nickname.",
		fakeDash: "You can't have weird versions of '-' in your nickname.",
		tsbug1: "Your nickname contains weird and broken characters due to Teamspeak string translation. Please only use normal letters to avoid this.",
		undefined: "Reason unknown",
		regionalIndicatorLetters: "Your nickname can't contain Regional Indicator Letters",
		middleFinger: "You can't show your middlefinger like that...",
		enclosedAlphanumerics: "Your nickname can't contain Enclosed Alphanumerics (Letters in circles)",
		enclosedAlphanumerics2: "Your nickname can't contain Enclosed Alphanumerics (Letters in brackets)",
		russianIdentical: "Your nickname can't contain characters Letters of the Russian (Cyrillic) Alphabet that look identical to the latin alphabet. Please replace all of these: АаВвЕеКкМмНнОоРрСсТтУуХхЅѕІіЈј with these: AaBbEeKkMmHhOoPpCcTtYyXxSsIiJj",
		political: "Your nickname can't contain certain political characters",
		pipes: "Your nickname can't contain Pipes (|)",
		modifiedCurrency: "Your nickname can't contain modified currency Characters",
		upsideDown: "Your nickname can't contain upside-down Characters",
		unclassified: "Your nickname contains invalid characters",
		circled: "Your nickname can't contain circled characters"
	}
}

const words = [
	// ["reason", "word"],

	// Probably spam, users should use something individual
		["speakus", reason.defaultName],
		["seakus", reason.defaultName],
		["new", reason.defaultName, 0b1],


	// Admin / Impersonation:
		["admin", reason.adminImpersonation],
		["serveradmin", reason.adminImpersonation],
		["owner", reason.adminImpersonation],
		["maingron", reason.impersonation],

	// Obscene:
		["nazi", reason.obscene],
		["fuck", reason.obscene],
		["penis", reason.obscene],
		["dick", reason.obscene, 0b0],
		["big dick", reason.obscene],
		["bitch", reason.obscene],
		["nig+er", reason.obscene],
		["kill yo", reason.obscene],
		["otherfuc", reason.obscene],
		["as+hole", reason.obscene],
		["ickhea", reason.obscene],
		["fuck off", reason.obscene],
		["acab", reason.obscene, 0b0111],
		["horny", reason.obscene],
		["shithead", reason.obscene],
		["porn", reason.obscene, 0b1111],
		["pornog", reason.obscene],
		["porny", reason.obscene],
		["rape", reason.obscene, 0b0101],
		["rapi", reason.obscene, 0b0101],
		["slut", reason.obscene, 0b1101],
		["arse", reason.obscene, 0b1111],
		["hitler", reason.obscene, 0b1001],
		["ieg hei", reason.obscene, 0b1001],
		["ocksuc", reason.obscene],


		// German:
		["hurensohn", reason.obscene],
		["huhrensohn", reason.obscene],
		["nutte", reason.obscene],
		["arsc", reason.obscene],
		["arsh", reason.obscene],
		["enisluts", reason.obscene],
		["scheiß", reason.obscene],
		["ecks+au", reason.obscene],
		["ficken", reason.obscene],
		["umslokal", reason.obscene],
		["fotze", reason.obscene],
		["wichs", reason.obscene],
		["issgebur", reason.obscene],
		["anzluts", reason.obscene]

];
